name: All branches CI

on:
  pull_request:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Install dependencies
      run: dotnet restore

    # Build all projects
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Execute all unit tests in the solution
    - name: Test
      run: dotnet test --no-restore --verbosity normal
